# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common-graphics/LA.UM.9.6.3.r1-06200-89xx.0/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/mithorium-common-graphics/daisy-Q

PRODUCT_COPY_FILES += \
    

PRODUCT_PACKAGES += \
    libGLESv2_adreno \
    libC2D2
